import mlx.core as mx

class Module:
    def __init__(self) -> None: ...
    @property
    def training(self) -> bool: ...
    def train(self, mode: bool = True) -> Module: ...
    def eval(self) -> Module: ...

class Linear(Module):
    weight: mx.array
    def __init__(self, input_dims: int, output_dims: int, bias: bool = True) -> None: ...
    def __call__(self, x: mx.array) -> mx.array: ...

class QuantizedEmbedding(Module):
    weight: mx.array
    scales: mx.array
    biases: mx.array | None
    group_size: int
    bits: int
    mode: str
    def __init__(
        self, num_embeddings: int, dims: int, group_size: int | None = None,
        bits: int | None = None, mode: str = "affine",
    ) -> None: ...
    def __call__(self, tokens: mx.array) -> mx.array: ...
    def as_linear(self, hidden: mx.array) -> mx.array: ...

def gelu_approx(x: mx.array) -> mx.array: ...
